application: cs-cheatsheet
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /modulelist_tags.html
  static_files: modulelist_tags.html
  upload: modulelist_tags\.html

- url: /libraries
  static_files: libraries.html
  upload: libraries\.html

- url:  /bower_components/
  static_dir: bower_components

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
